cmd/server.go

This will enable CPU & memory profiles with the pprof Go tool.

Add pprof handlers to HTTPS interface

---

cmd/server.go
lib/config.go

This also actually exposes pprof. A previous commit assumed that pprof
was exposed with the existing mux, but it wasn't.

Serve pprof on a different port

---

cmd/build.go
cmd/server.go
lib/builder.go
lib/config.go
lib/github_fetch.go

Github repos were passed around with in-memory io.Readers. When
dealing with large repositories, this overhead can be very large,
especially when handling concurrent jobs. According to a pprof profile
of Furan, its memory usage can exceed 500MB for significant periods of
time.
This changeset introduces a `tempTarball`, which is a disk-backed
tempfile implementing `io.ReadCloser` that has custom `.Close()`
behavior: the underlying file is deleted upon closing. `GithubFetcher`
was changed to back all tarballs with `tempTarball`. Additionally, a
`.Close()` call is made everywhere Github archives are downloaded.

Back Github repo tarballs with files (closes #23)

---

cmd/build.go
cmd/server.go
lib/builder.go
lib/config.go
lib/github_fetch.go
lib/github_fetch_test.go

Previously, the tar file prefixes would be stripped in one go, which
requires filling up an entire buffer, regardless of whether it is
in-memory or file backed. The implementation has now been changed to
use a pipe, so tar file prefixes are stripped lazily when the `.Read`
method is called on a `tarPrefixStripper`. Since a pipe is now used, memory
usage will now be minimal because the tarball is read as needed and
all processing is performed on the fly.

Strip Github tar file prefixes in a stream

---

cmd/monitor.go

Add a `monitor` subcommand to monitor an already-triggered running build.

monitor CLI command

---

.gitignore
Makefile

This commit introduces a Makefile task that creates a Furan release
for amd64 darwin & linux platforms. The output of the task is two
gzipped tarballs (one per platform) can be uploaded to Github.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dollarshaveclub/furan/46)

Create release Makefile task

---

Gopkg.lock
lib/tagcheck/tagcheck.go
lib/tagcheck/tagcheck_test.go
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTING.md
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/README.md
vendor/golang.org/x/sync/codereview.cfg
vendor/golang.org/x/sync/errgroup/errgroup.go
vendor/golang.org/x/sync/errgroup/errgroup_example_md5all_test.go
vendor/golang.org/x/sync/errgroup/errgroup_test.go
vendor/golang.org/x/sync/semaphore/semaphore.go
vendor/golang.org/x/sync/semaphore/semaphore_bench_test.go
vendor/golang.org/x/sync/semaphore/semaphore_example_test.go
vendor/golang.org/x/sync/semaphore/semaphore_test.go
vendor/golang.org/x/sync/singleflight/singleflight.go
vendor/golang.org/x/sync/singleflight/singleflight_test.go
vendor/golang.org/x/sync/syncmap/map.go
vendor/golang.org/x/sync/syncmap/map_bench_test.go
vendor/golang.org/x/sync/syncmap/map_reference_test.go
vendor/golang.org/x/sync/syncmap/map_test.go

When a repository has a large number of tags (in our case, > 10k) a full tag list API call can take upwards of several minutes to complete.
Instead of pulling full tags (which has an overhead proportional to the number of extant tags), this switches tagcheck to attempt to pull a manifest for each tag and detects whether the API returns an error. This still has a bit more overhead than would be ideal (~1 second per tag, using quay.io) but it much better than a full tag dump.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dollarshaveclub/furan/49)

tagcheck: switch to manifest API call

---

local_dev_secrets.json

Not having this value in vault causes Furan to terminate. 
Just throwing up this PR as a workaround for https://github.com/dollarshaveclub/furan/issues/56, if anyone needs a fix until the underlying issue is resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dollarshaveclub/furan/60)

docker compose: add default/fake api key required for docker compose

---

.helm/charts/furan/templates/deployment.yaml
.helm/charts/furan/values.yaml

There seems to be some implicit behavior during `helm upgrade` that will basically merge values from the default value file found from the chart if the externally supplied value file does not contain the corresponding value. 
This PR adds a boolean value to specify whether we should us consul discovery or use the supplied list of db nodes. It also adds some explicit equality checks to better understand the types of certain values in a template.

helm: use explicit boolean guards for flags

---

.helm/charts/furan/templates/deployment.yaml
lib/datalayer/datalayer.go
lib/grpc/grpc.go

This PR addresses 2 issues. 
1. There are some duplicate operations as a result from a copy/paste error. 
2. The naming scheme for the operations are inconsistent across the repo.
3. Update tracing agent helm chart parameter in furan deployment template.

datadog apm: update incorrect operation names

---

lib/builder/builder.go
lib/grpc/grpc.go

PR does 3 things
1. Avoid overlapping spans during furan push operation
2. Propagate error messages properly from failed docker build events
3. Only report errors that correspond to build failures to datadog apm. We do not want datadog apm to count things like "Build not necessary" as an error for a trace.

Build not necessary error filtering

---

lib/buildcontext/buildcontext.go
lib/builder/builder.go
lib/grpc/grpc.go

I'm stupid and didn't realize that the datadog tracer package came with some helper functions for creating contexts with spans, and extracting spans from contexts. This will put us in a better place for enabling distributing tracing.

datadog apm: utilize datadog tracer context functions

---

lib/builder/builder.go
lib/errors/errors.go
lib/errors/errors_test.go
lib/grpc/grpc.go

closes https://github.com/dollarshaveclub/furan/issues/73
**Summary**
- Allow `UserError` type to be wrapped and unwrapped properly
- Ensure that we check that the cancellation wasn't cancelled during IO operations in which it is likely to be cancelled. Then return a `UserError` so that we can not trigger alerts based off these cancellations. There are probably more occurrences of this that we may need to change in later PRs if we do run into those issues. 
- Start wrapping errors in the Build method so that we can preserve the root cause (in order to check if it is a user error).

issue 73: label cancelled builds as user error

---

cmd/build.go
cmd/root.go
cmd/server.go

Noticed during the last canary deployment that some of the datadog apm service names weren't being set properly. This resolves the issue.

Properly set datadog service names

---

rpcclient/rpcclient.go

We do not use the furan client within this repo, however, Acyl does use it. 
There are multiple spots where we have to call `NewFuranClient` within Acyl, mostly due to the Nitro feature flag. 
This patch allows us to have a simpler means of configuring the client. As opposed to having to keep track of a consistent datadog service name for the furan client specifically, we can just use the datadog service name prefix that is passed in as a command line argument to Acyl, and then let the furan client decide its service name suffix.

rpcclient: modify datadog service name configuration

---

.gitignore
.helm/charts/furan/templates/deployment.yaml
.helm/charts/furan/values.yaml

We previously replaced the `k8s_auth` value with `useK8sAuth`. This PR updates deployment manifest to use the correct value.

helm: fix incorrect value name in chart template

---

lib/datalayer/datalayer.go

With the current implementation, newer versions of scylladb seem to respond in a manner that makes gocql respond with the error: `not enough columns to scan into: have 8 want 16`. 
It appears that when we initially insert the data, we are scanning the values from each BuildRequest field individually. When we fetch the data, we should be scanning the values in the same manner.

fix: scan request udt how gocql expects

---

cmd/cancel.go
cmd/trigger.go
lib/metrics/metrics.go
lib/mocks/mock_metrics_collector.go

Currently, all of the metric collection is done server side. This is useful for most scenarios. 
However, one potential use case for Furan is to use `furan trigger` within some pipeline. `furan trigger` can fail even if the server was able to build and push the image successfully. This is because it communicates the server to check on the status of the build (which can fail). 
This patch adds the ability to collect metrics from the `furan trigger` command itself. This way, users can add monitors around this metric and act accordingly. 
If for some reason, the `MetricsCollector` fails to be created, the `trigger` command will just continue to operate the same as it did before.

cmd: add monitoring around trigger cmd

---

.helm/charts/consul/templates/service.yaml
.helm/charts/furan/templates/deployment.yaml
.helm/charts/furan/values.yaml
.helm/charts/kafka/templates/deployment.yaml
.helm/charts/kafka/templates/service.yaml
.helm/charts/kafka/values.yaml
.helm/charts/scylladb/templates/configmap.yaml
.helm/charts/scylladb/templates/deployment.yaml
.helm/charts/scylladb/templates/service.yaml
.helm/charts/scylladb/values.yaml
.helm/charts/vault/templates/service.yaml
.helm/charts/vault/values.yaml
.helm/charts/zookeeper/templates/service.yaml
acyl.yml
cmd/server.go
lib/config/config.go
lib/metrics/fake.go
lib/metrics/metrics.go

Various fixes needed to include Furan as a repo-style dependency in local Acyl DQA environments (minikube, etc) to allow them to function fully.
- Add `--disable-metrics` CLI flag to allow Furan to not error out when Datadog isn't available.
- Conditionally prefix all service names with `furan-` to make Furan dependencies discoverable and private when included as transitive dependencies.
- Greatly reduce DinD resource requests to make it schedulable in a local k8s cluster.

Local Acyl environment fixes

---

.helm/charts/furan/templates/deployment.yaml
.helm/charts/furan/values.yaml

Max found an issue where the MTU being used by Docker was greater than the MTU set for the underlying interface.
To solve this issue, we should make this MTU value configurable to allow developers to set this value as needed. 
Issue described in detail in a few different blogs: 
https://mlohr.com/docker-mtu/

helm: add mtu value for dind container

---

.circleci/config.yml
cmd/runbuild.go
migrations/0001_initial.up.sql
pkg/builder/builder.go
pkg/buildkit/buildkit.go
pkg/datalayer/testsuite/testsuite.go

Tweaks to make build handoff more robust
- Check the buildkitd socket is available earlier, before handoff
- Handle signals after handoff and abort build cleanly

Better job handoff
